### ISSUE TITLE
Avahi 0.6.32 no longer builds on OS X Snow Leopard (10.6) (MacPorts)

### ISSUE THREAD

**Issue by rlhamil** [lathiat/avahi#102]
It seems it's now using O_CLOEXEC, which isn't supported in older OS versions; the usual alternative is  to open the file, and then use fctl(fd, F_SETFD,  FD_CLOEXEC).

_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_net_avahi/avahi/work/avahi-0.6.32/avahi-daemon'
:info:build   CC       avahi_daemon-main.o
:info:build   CC       avahi_daemon-simple-protocol.o
:info:build main.c: In function ‘get_machine_id’:
:info:build main.c:590: error: ‘O_CLOEXEC’ undeclared (first use in this function)
:info:build main.c:590: error: (Each undeclared identifier is reported only once
:info:build main.c:590: error: for each function it appears in.)
:info:build main.c: In function ‘get_machine_id’:
:info:build main.c:590: error: ‘O_CLOEXEC’ undeclared (first use in this function)
:info:build main.c:590: error: (Each undeclared identifier is reported only once
:info:build main.c:590: error: for each function it appears in.)

**Comment by BrentSqAR** [comment]
and line 592 too:

    fd = open("/etc/machine-id", O_RDONLY|O_CLOEXEC|O_NOCTTY);
    if (fd == -1 && errno == ENOENT)
        fd = open("/var/lib/dbus/machine-id", O_RDONLY|O_CLOEXEC|O_NOCTTY);
    if (fd == -1)
        return NULL;

**Comment by kencu** [comment]
This function opens a file, reads in some data, then closes the file. It doesn't call an exec function, and doesn't look like it will split off into a thread or fork. Is the O_CLOEXEC doing something here of importance? Perhaps the flag could just be deleted, or alternatively, just define O_CLOEXEC to 0 on systems that don't support it. Does this seem realistic?

```static char *get_machine_id(void) {
    int fd;
    char buf[32];

    fd = open("/etc/machine-id", O_RDONLY|O_CLOEXEC|O_NOCTTY);
    if (fd == -1 && errno == ENOENT)
        fd = open("/var/lib/dbus/machine-id", O_RDONLY|O_CLOEXEC|O_NOCTTY);
    if (fd == -1)
        return NULL;

    /* File is on a filesystem so we never get EINTR or partial reads */
    if (read(fd, buf, sizeof buf) != sizeof buf) {
        close(fd);
        return NULL;
    }
    close(fd);
```

**Comment by warmsocks** [comment]
> This function opens a file, reads in some data, then closes the file. It doesn't call an exec function, and doesn't look like it will split off into a thread or fork. Is the O_CLOEXEC doing something here of importance? Perhaps the flag could just be deleted, or alternatively, just define O_CLOEXEC to 0 on systems that don't support it. Does this seem realistic?

I had the same issue with O_CLOEXEC being undefined when updating an older PowerPC embedded system with an even older version of gcc to Avahi 0.6.32.

I reviewed the two uses of O_CLOEXEC and came to the same conclusion.  I don't know why it's there, other than as a defensive programming practice.  I believe it is safe to remove it or define it to 0 as @kencu suggests.

**Comment by evverx** [comment]
I wonder if this issue is still relevant?

As far as I can see it was patched in https://github.com/macports/macports-ports/commit/24673aac9ff9a839144b4f4e19bb03c36fda5814 7 years ago and the patch is still there but those macOS versions have been EOLed so I'm not sure if that patch is still needed.

More generally I think if avahi is built on macOS it would maybe make sense to set up sort some of CI upstream to make sure that it's buildable there at least (macOS is supported on GitHub actions) and try to fix things if it isn't buildable. Currently avahi is tested on Linux only.
